In [32]:
import librosa
import numpy as np
import os

In [17]:
path = './Datasets/RawData/'
mylist = os.listdir(path)
print("Path has %d files" %(len(mylist)))

Path has 1380 files


In [19]:
def extract_mfccs(filename):
    audio, Fs = librosa.load(filename, duration=2.25, sr=22050, offset=0.5)
    features = librosa.feature.mfcc(y=audio, sr=22050, n_mfcc = 40)
    
    return features

In [22]:
labels = []
feeling_nos = ['01','02','04','05']
feeling_labels = [0,1,2,3]
feeling_names = ['neutral', 'happy', 'sad', 'angry']
feeling_map = dict(zip(feeling_nos, feeling_labels))
count = [0,0,0,0]
print(feeling_map)
flag = 1
for full_filename in mylist:
    
    filename = full_filename[0:20]
    # print(filename)

    filename=filename.split('-')
    # print(filename)
    emotion = filename[2]
    if emotion in feeling_map:
        labels.append(feeling_map[emotion]) 
        if flag == 1:
            i = 0
            temp = np.mean(extract_mfccs(path+full_filename), axis=0)
            mfccs = np.ndarray((644,temp.shape[1]))
            flag = 0
        
        print(i,full_filename, temp.shape)
        temp = np.mean(extract_mfccs(path+full_filename), axis=0)
        mfccs[i,:] = temp.T
        i=i+1

print(labels)

{'01': 0, '02': 1, '04': 2, '05': 3}
0 03-01-01-01-01-01-01.wav (97,)
1 03-01-01-01-01-01-02.wav (97,)
2 03-01-01-01-01-01-03.wav (97,)
3 03-01-01-01-01-01-04.wav (97,)
4 03-01-01-01-01-01-06.wav (97,)
5 03-01-01-01-01-01-07.wav (97,)
6 03-01-01-01-01-01-08.wav (97,)
7 03-01-01-01-01-01-09.wav (97,)
8 03-01-01-01-01-01-10.wav (97,)
9 03-01-01-01-01-01-11.wav (97,)
10 03-01-01-01-01-01-12.wav (97,)
11 03-01-01-01-01-01-13.wav (97,)
12 03-01-01-01-01-01-14.wav (97,)
13 03-01-01-01-01-01-15.wav (97,)
14 03-01-01-01-01-01-16.wav (97,)
15 03-01-01-01-01-01-17.wav (97,)
16 03-01-01-01-01-01-18.wav (97,)
17 03-01-01-01-01-01-19.wav (97,)
18 03-01-01-01-01-01-20.wav (97,)
19 03-01-01-01-01-01-21.wav (97,)
20 03-01-01-01-01-01-22.wav (97,)
21 03-01-01-01-01-01-23.wav (97,)
22 03-01-01-01-01-01-24.wav (97,)
23 03-01-01-01-01-02-01.wav (97,)
24 03-01-01-01-01-02-02.wav (97,)
25 03-01-01-01-01-02-03.wav (97,)
26 03-01-01-01-01-02-04.wav (97,)
27 03-01-01-01-01-02-06.wav (97,)
28 03-01-01-01-01-02-

237 03-01-02-02-02-01-09.wav (97,)
238 03-01-02-02-02-01-10.wav (97,)
239 03-01-02-02-02-01-11.wav (97,)
240 03-01-02-02-02-01-12.wav (97,)
241 03-01-02-02-02-01-13.wav (97,)
242 03-01-02-02-02-01-14.wav (97,)
243 03-01-02-02-02-01-15.wav (97,)
244 03-01-02-02-02-01-16.wav (97,)
245 03-01-02-02-02-01-17.wav (97,)
246 03-01-02-02-02-01-18.wav (97,)
247 03-01-02-02-02-01-19.wav (97,)
248 03-01-02-02-02-01-20.wav (97,)
249 03-01-02-02-02-01-21.wav (97,)
250 03-01-02-02-02-01-22.wav (97,)
251 03-01-02-02-02-01-23.wav (97,)
252 03-01-02-02-02-01-24.wav (97,)
253 03-01-02-02-02-02-01.wav (97,)
254 03-01-02-02-02-02-02.wav (97,)
255 03-01-02-02-02-02-03.wav (97,)
256 03-01-02-02-02-02-04.wav (97,)
257 03-01-02-02-02-02-06.wav (97,)
258 03-01-02-02-02-02-07.wav (97,)
259 03-01-02-02-02-02-08.wav (97,)
260 03-01-02-02-02-02-09.wav (97,)
261 03-01-02-02-02-02-10.wav (97,)
262 03-01-02-02-02-02-11.wav (97,)
263 03-01-02-02-02-02-12.wav (97,)
264 03-01-02-02-02-02-13.wav (97,)
265 03-01-02-02-02-0

473 03-01-05-01-01-01-15.wav (97,)
474 03-01-05-01-01-01-16.wav (97,)
475 03-01-05-01-01-01-17.wav (97,)
476 03-01-05-01-01-01-18.wav (97,)
477 03-01-05-01-01-01-19.wav (97,)
478 03-01-05-01-01-01-20.wav (97,)
479 03-01-05-01-01-01-21.wav (97,)
480 03-01-05-01-01-01-22.wav (97,)
481 03-01-05-01-01-01-23.wav (97,)
482 03-01-05-01-01-01-24.wav (97,)
483 03-01-05-01-01-02-01.wav (97,)
484 03-01-05-01-01-02-02.wav (97,)
485 03-01-05-01-01-02-03.wav (97,)
486 03-01-05-01-01-02-04.wav (97,)
487 03-01-05-01-01-02-06.wav (97,)
488 03-01-05-01-01-02-07.wav (97,)
489 03-01-05-01-01-02-08.wav (97,)
490 03-01-05-01-01-02-09.wav (97,)
491 03-01-05-01-01-02-10.wav (97,)
492 03-01-05-01-01-02-11.wav (97,)
493 03-01-05-01-01-02-12.wav (97,)
494 03-01-05-01-01-02-13.wav (97,)
495 03-01-05-01-01-02-14.wav (97,)
496 03-01-05-01-01-02-15.wav (97,)
497 03-01-05-01-01-02-16.wav (97,)
498 03-01-05-01-01-02-17.wav (97,)
499 03-01-05-01-01-02-18.wav (97,)
500 03-01-05-01-01-02-19.wav (97,)
501 03-01-05-01-01-0

In [25]:
from sklearn.preprocessing import OneHotEncoder
from keras.utils import np_utils
y = np_utils.to_categorical(labels)
print(y.shape)
print(y)

(644, 4)
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


In [26]:
import random
print(y.shape[0])
np.random.seed(1)
shuffled_indices = np.arange(y.shape[0])
np.random.shuffle(shuffled_indices)
print(shuffled_indices)

644
[361 441 458 386 502 457 541 573 116 506 179  23 641 484 101  66 284 352
 223  88  59 559 480 388  41 301 452  92 428 273 528  13 599 602 609 159
 475 335 333  69  60 446 119 354  85  47 527 616 160 236 517 195  82 346
 318 132 224 312 260 107 402 242 604 311 429  34 340 619 337 597 598 463
 613 165   0  17 426 523 472 285 427 241 592 494 148  65  11 134 328 181
 353 540 417 111 614 538 365 531 345 442 628 449 376 396  49 185 197 537
 135 415 289 639 304 504 586 120 323 406 414 440 587 255 268 611 245  62
 201 274 380 488 349 379 499  90 250  29 626 543 422 377 578 595 218 259
 103 629 233  80 262 368   3 173   9 247 207 339 383 314 363 277 606 261
  40 581   5 423 570  38 636 257 292 172 162  67 124  39 467 622 526 147
 373 419 512 359 460  31 370 511  95 306 425 187 433 146 214  74 375 364
  61 286 385  76 293 355 186 329  68 438 582 118   4 632 623 395 448  19
 392 200 378 612 117 545  78  56  57 180 439  42 121 360  81 133 407 350
 525 161 404 533 347 192 584 483 571 305 487 43

In [27]:
train_indices = shuffled_indices[np.arange(int(y.shape[0]*0.8))]
test_indices = np.array(list(set(shuffled_indices) - set(train_indices)))
print(test_indices.shape)
print(train_indices.shape)

(129,)
(515,)


In [28]:
y_train = y[train_indices]
x_train = mfccs[train_indices]
y_test = y[test_indices]
x_test = mfccs[test_indices]

print(y_train.shape)
print(y_test.shape)
print(x_train.shape)
print(x_test.shape)

(515, 4)
(129, 4)
(515, 97)
(129, 97)


In [31]:
np.save('./Datasets/x_train.npy',x_train)
np.save('./Datasets/x_test.npy',x_test)
np.save('./Datasets/y_train.npy',y_train)
np.save('./Datasets/y_test.npy',y_test)